// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwTZgX8xpUfpUXtQ9wFDakg69zY54D1L0',
    appId: '1:881556254347:web:658204ab39572488952e8e',
    messagingSenderId: '881556254347',
    projectId: 'al-pura-yepes',
    authDomain: 'al-pura-yepes.firebaseapp.com',
    storageBucket: 'al-pura-yepes.firebasestorage.app',
    measurementId: 'G-33GCPE46KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh7IG2A_EdjDT2rYEMVFaOYhipvmAwYtE',
    appId: '1:881556254347:android:88b480120b5f1bdb952e8e',
    messagingSenderId: '881556254347',
    projectId: 'al-pura-yepes',
    storageBucket: 'al-pura-yepes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnNoQ7oIifMaP2K82PqNokXKnH-6xFrBg',
    appId: '1:881556254347:ios:a4e3e1533da25fcb952e8e',
    messagingSenderId: '881556254347',
    projectId: 'al-pura-yepes',
    storageBucket: 'al-pura-yepes.firebasestorage.app',
    iosBundleId: 'com.example.alPuraFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnNoQ7oIifMaP2K82PqNokXKnH-6xFrBg',
    appId: '1:881556254347:ios:a4e3e1533da25fcb952e8e',
    messagingSenderId: '881556254347',
    projectId: 'al-pura-yepes',
    storageBucket: 'al-pura-yepes.firebasestorage.app',
    iosBundleId: 'com.example.alPuraFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwTZgX8xpUfpUXtQ9wFDakg69zY54D1L0',
    appId: '1:881556254347:web:cb1f49aef805867d952e8e',
    messagingSenderId: '881556254347',
    projectId: 'al-pura-yepes',
    authDomain: 'al-pura-yepes.firebaseapp.com',
    storageBucket: 'al-pura-yepes.firebasestorage.app',
    measurementId: 'G-ELDXGF3DR1',
  );

}